server:
  # \u7AEF\u53E3\u53F7
  port: 8201

spring:
  application:
    # \u670D\u52A1\u540D
    name: service-hosp

  profiles:
    # \u73AF\u5883\u6FC0\u6D3B
    active: dev

  # mysql \u53CA \u8FDE\u63A5\u6C60\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource # \u4F7F\u7528 Hikari \u8FDE\u63A5\u6C60\u65F6\uFF0Ctype \u53EF\u7701\u7565

  # \u8FD4\u56DE json \u7684\u5168\u5C40\u65F6\u95F4\u683C\u5F0F\uFF0C\u4F1A\u5931\u6548\uFF0C\u9700\u8981\u91CD\u5199\u914D\u7F6E\u7C7B
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

# mybatis-plus \u8BBE\u7F6E
mybatis-plus:
  configuration:
    # \u663E\u793A sql \u6267\u884C\u76F8\u5173\u7684\u5177\u4F53\u65E5\u5FD7\u4FE1\u606F
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
